M48
; DRILL file {KiCad (6.99.0-2504-g6a9c6e8599)} date Thursday, September 14, 2023 at 12:08:57 AM
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-14T00:08:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.99.0-2504-g6a9c6e8599)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X6.005Y-3.345
X6.635Y-3.875
T0
M30
