name: Deploy to GitHub Pages

on:
  push:
    branches:
      - squash 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install jq for JSON parsing
      run: sudo apt-get install jq

    - name: Read svg_list.json and Create HTML
      run: |
        echo '<html><head><title>SVG List</title></head><body><h1>SVG Files:</h1><ul>' > index.html
        jq -r '.[] | "<li>" + .name + " - " + .description + "</li>"' gerbers/svg_list.json >> index.html
        echo '</ul></body></html>' >> index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # The directory where your index.html file is located

