name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # replace with your default branch if it's not 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Generate index.html
      run: |
        echo '<html><head><title>SVG List</title></head><body><h1>SVG Files:</h1><ul>' > index.html
        cat gerbers/svg_list.json | jq -r '.[] | "<li>" + .name + " - " + .description + "</li>"' >> index.html
        echo '</ul></body></html>' >> index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # this will publish all files in the current directory to GitHub Pages

